import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties
import java.net.URI

val localProperties = Properties()

val localPropertiesFile =
    rootProject.file("local.properties")

if (localPropertiesFile.exists()) {

    localPropertiesFile.inputStream().use(localProperties::load)
}

val devToken: String = localProperties.getProperty("DEV_TOKEN")?.trim() ?: ""

// Command-line/Gradle property takes precedence over the developer's local file.
val backendBaseUrl = providers.gradleProperty("BACKEND_BASE_URL").orNull
    ?.trim()?.takeIf { it.isNotEmpty() }
    ?: localProperties.getProperty("BACKEND_BASE_URL")?.trim()?.takeIf { it.isNotEmpty() }
    ?: "http://10.0.2.2:8080"

val generateBackendConfig = tasks.register("generateBackendConfig") {
    val outputDir = layout.buildDirectory.dir("generated/backendConfig")
    val configuredUrl = backendBaseUrl
    inputs.property("backendBaseUrl", configuredUrl)
    outputs.dir(outputDir)
    doLast {
        val uri = try {
            URI(configuredUrl)
        } catch (_: Exception) {
            throw GradleException("BACKEND_BASE_URL must be an absolute http(s) URL.")
        }
        require(uri.scheme in setOf("http", "https") && !uri.host.isNullOrBlank()
                && uri.userInfo == null && uri.query == null && uri.fragment == null
                && (uri.port == -1 || uri.port in 1..65535)) {
            "BACKEND_BASE_URL must be an absolute http(s) URL without credentials, query or fragment."
        }
        val literal = uri.toASCIIString().trimEnd('/')
            .replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        val file = outputDir.get().file("com/proyecto_final/triage/config/BackendConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.proyecto_final.triage.config

            // Generated by Gradle. Configure BACKEND_BASE_URL instead of editing this file.
            internal object BackendConfig {
                const val BASE_URL = "$literal"
            }
            """.trimIndent()
        )
    }
}

val generateDevToken = tasks.register("generateDevToken") {
    val outputDir = layout.buildDirectory.dir("generated/devToken")
    val tokenValue = devToken
    val refreshTokenValue = project.findProperty("DEV_REFRESH_TOKEN") as String? ?: ""
    inputs.property("devToken", tokenValue)
    inputs.property("devRefreshToken", refreshTokenValue)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/proyecto_final/triage/config/DevToken.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.proyecto_final.triage.config

            object DevToken {
                const val TOKEN = "$tokenValue"
                const val REFRESH_TOKEN = "$refreshTokenValue"
            }
            """.trimIndent()
        )
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompileTool>().configureEach {
    dependsOn(generateDevToken)
    dependsOn(generateBackendConfig)
}

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    kotlin("plugin.serialization") version "2.0.0"
    id("org.sonarqube") version "7.3.1.8318"
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }
    
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }
    
    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.android)
            implementation(libs.maps.compose)
            implementation(libs.play.services.maps)
            implementation(libs.androidx.core.splashscreen)
            implementation(libs.play.services.location)
            implementation(libs.android.sdk)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.voyager.navigator)
            implementation(libs.voyager.screenmodel)
            implementation(libs.voyager.lifecycle.kmp)
            implementation(libs.material.icons.extended)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.compose.foundation)
            implementation(libs.kotlinx.datetime)
            implementation(libs.cmpfilepicker)
            implementation(libs.ktor.client.auth)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

kotlin.sourceSets.commonMain.get().kotlin.srcDir(layout.buildDirectory.dir("generated/devToken"))
kotlin.sourceSets.commonMain.get().kotlin.srcDir(layout.buildDirectory.dir("generated/backendConfig"))

android {
    namespace = "com.proyecto_final.triage"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.proyecto_final.triage"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
        manifestPlaceholders["MAPS_API_KEY"] =
            localProperties.getProperty(
                "MAPS_API_KEY"
            )

        buildConfigField(
            "String",
            "AUTH0_CLIENT_ID",

            "\"${localProperties.getProperty("AUTH0_CLIENT_ID")}\""
        )
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    debugImplementation(libs.compose.uiTooling)
}

